### ISSUE TITLE
what's in a name...

### ISSUE THREAD

**Issue by pfcgroot** [hermes-router/hermes#2]
Dear development team,

Interesting project that could be very useful in academic and research settings. When properly implemented, it could even be a interesting alternative for applications like CTP. 

Just one note about the name of the project: are you aware that there is already a well know (commercial) product/company with the same name in medical imaging world? Just google hermes and dicom, and you'll see...

Kind regards,
Paul

**Comment by tblock79** [comment]
Thanks for the heads-up, Paul! We chose Hermes as internal project name without spending much time on due diligence, as we initially didn't have the plan to make it publicly available. However, after finishing the first version, we decided to release it as open-source tool, as it seemed useful for other groups as well. In the long term, we might have to think about a new name. For now, we added a remark to the documentation that the project is not related to the software company that you have pointed out.

Best,
  Tobias

**Comment by pfcgroot** [comment]
Hi Tobias,

Thanks for the feedback. Good to know the background and status of the
development proces. I really like the combination of using the rather
reliable dcmtk software with a Python management layer. Looks very
promising...

Best
Paul



Op ma 7 okt. 2019 17:09 schreef Tobias Block <notifications@github.com>:
