### ISSUE TITLE
Any reason why password for new users is of pattern [A-Za-z0-9]?

### ISSUE THREAD

**Issue by joshy** [hermes-router/hermes#4]
Hi Tobias,
I can't enter a password with special characters because of required input pattern [A-Za-z0-9]. This restriction should be lowered (imho).

Best regards,
Joshy

**Comment by tblock79** [comment]
Hi Joshy, 

I believe that I was concerned that entering a " character within the password could break the JSON parser, but it seems that it is properly escaping " characters. Thus, I removed the input pattern for the next version.

Best,
  Tobias
