### ISSUE TITLE
menus disappear if window not wide enough

### ISSUE THREAD

**Issue by dmd** [hermes-router/hermes#6]
![image](https://user-images.githubusercontent.com/41439/77778545-8a076f80-7027-11ea-840c-8df5b8f1071e.png)

If the window isn't wide enough, menus disappear completely.  It took me quite a while to figure out that there were menus.

**Comment by tblock79** [comment]
Checked the UI behavior with the current DEV version 0.2. UI switches to a hamburger menu if the menu items don't fit, as intended. Threshold seems correct (the DEV version has more entries than the stable version).
