### ISSUE TITLE
port dicom receive

### ISSUE THREAD

**Issue by ramonsousa89** [hermes-router/hermes#9]
I installed HERMES correctly
and now i want to know how do i send it to the dicom router
which port receives DICOM and AE?
how do i modify the door?
I did not find this information from the dicom receiving port

**Comment by tblock79** [comment]
In version 0.1, the port is defined in the last line of file /hermes/receiver.sh (by default, it is 104). In the next version, this can be configured in the Configuration section. Hermes does not require a specific AE and will accept any images.
